dist: trusty

services:
  - docker

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: TYPE=coverage
  # More PHP instances with different environment variables may be added here
  # This may be useful if a additional PHP versions or DBMS (SQLite, ...) should be tested by Travis

install:
  - travis_retry make install-php

script:
  - make install-php
  - make ci-with-coverage
  - make install-php COMPOSER_FLAGS="--no-dev -q" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm phpstan/phpstan analyse -c phpstan.travis.neon --level 7 --no-progress src/ # Can't use "make stan" because stan was removed

after_success:
  - if [ "$TYPE" == "coverage" ]; then bash build/travis/uploadCoverage.sh; fi

cache:
  directories:
    - "$HOME/.composer/cache"

notifications:
  email:
    on_success: change
    on_failure: always
