services:
  app_debug:
    image: "registry.gitlab.com/fun-tech/fundraising-frontend-docker:xdebug"
    environment:
      - XDEBUG_CONFIG=remote_host=${LOCAL_IP}
      - PHP_IDE_CONFIG=serverName=address_change.spenden.wikimedia.de
    expose:
      - "9000" # PHP-FPM
    volumes:
      - ./:/code
    working_dir: /code
    links:
      - database