version: '3.4'

services:
  app_debug:
    image: "wikimediade/fundraising-frontend:xdebug"
    environment:
      - XDEBUG_CONFIG=remote_host=${LOCAL_IP}
      - PHP_IDE_CONFIG=serverName=address_change.spenden.wikimedia.de
    expose:
      - "9000" # PHP-FPM
    volumes:
      - ./:/code
    working_dir: /code
    links:
      - database